### ISSUE TITLE
Benchmark Testing

### ISSUE THREAD

**Issue by daftspunk** [tokenized/smart-contract#12]
### System configuration

- Network: Testnet
- Double Spend Detection Phase: 2 seconds

### Tests to perform

- [ ] The time it takes for a Transfer action to settle end to end
- [ ] How many actions the contract can process per second
- [ ] Percentage of successful double spends **before** detection phase (<2 sec)
- [ ] Percentage of successful double spends **after** detection phase (>2 sec)
- [ ] Percentage of double spends detected during the detection phase compared to how many double spends were broadcast (how good the detector is at detecting)

### Notes

- The test will have to be robust enough to account for different nodes receiving the message in the first hop. Proposal: modify the shotgun, so instead of blasting it to all nodes, pick one at random

- We should only include sampling and broadcasting to nodes that are mining nodes so we'll need to manage a list of nodes with hash power and monitor it over time

**Comment by eamesyi** [comment]
When calculating the number of actions the smart contract can process per second, please ensure that we test under the following conditions:
1. use the transfer/settlement actions
2. assume that there are 4 token receive addresses and 2 asset types (token for token) being swapped
3. an identity oracle is used for verifying the token receiving addresses.  This is only important for the validation of the Oracle produced signed messages by the smart contract.
