### ISSUE TITLE
[SpyNode] Broadcast TX without boot

### ISSUE THREAD

**Issue by daftspunk** [tokenized/smart-contract#18]
A light method to broadcast transactions without fully booting the SpyNode (via `.Run()`) would be useful in supplementing an RPC interfaced method for the same action.

### Current functionality

At the moment when you create an instance of SpyNode and call the `SpyNode.BroadcastTx` function the process will hang.

### Proposal / Expected functionality

Although the SpyNode is not running, it still should support broadcasting transactions.

Alternatively, a light mode could be introduced that uses minimal resources (storage and CPU) and still allows broadcasting transactions.

**Comment by KarlTheProgrammer** [comment]
Check out the smartcontract CLI usage of spynode.ShotgunTransmitTx. It requires setting up the spynode, but not starting it.

https://github.com/tokenized/smart-contract/blob/1a4bbcfe67df6eee0f308e5607859efaaaf7a851/cmd/smartcontract/client/node.go#L211
