### ISSUE TITLE
Is there an interface in the code?

### ISSUE THREAD

**Issue by nullcanon** [tokenized/smart-contract#2]
Hi,I want to do a "action",as I want to issue a number of Tokens,What should I do?Is there an interface in the code? Thanks a lot!

**Comment by daftspunk** [comment]
`smartcontractd` doesn't have an interface, although `smartcontract` is intended to be a CLI eventually. At the moment the code here is available for review (as code) but we don't expect people will be running it in the short term.

We are hoping to release the wallet source code or executable in the near future. This will act as the graphical interface and allow you to get up and running, hosting your own tokens. Stay tuned for the announcement around this.

Thanks!

**Comment by nullcanon** [comment]
Ok, Thanks for your answer.

**Comment by nullcanon** [comment]
@daftspunk Ok, Thanks for your answer.
