### ISSUE TITLE
Rebuilding chain with conflicting requests

### ISSUE THREAD

**Issue by KarlTheProgrammer** [tokenized/smart-contract#48]
1. Two conflicting transfer requests are sent, and only one is seen and approved by the smart contract. 
2. Smart contract is shut down, all local data is cleared, and it is restarted.
3. Smart contract rebuilds all data from the chain, it sees the previously unseen request first and builds an approval, because it hasn't seen the other request yet.
4. It sees the second request and it's approval, but doesn't know that conflicts with the first request.
5. When it gets in sync it knows it hasn't responded to the first request, so it sends that approval.

To fix it we need to check for conflicts between previously seen and unseen approval responses when rebuilding the state from on chain data.

**Comment by daftspunk** [comment]
Fixed by 590259d1c24dc32c294f847bb6cda06ee3198e4e / #49 

Nice edge case fix!
