### ISSUE TITLE
Move handler tests to tests directory

### ISSUE THREAD

**Issue by daftspunk** [tokenized/smart-contract#8]
Since the node handlers are all public interfaces, we should be testing from the outside.

```
cmd/smartcontractd/handlers
cmd/smartcontractd/listeners
cmd/smartcontractd/tests <--- place tests here
main.go
```

**Comment by daftspunk** [comment]
Refs ce1045d3c88947b7beb237a714900d156e8cfb09
Refs 128c983e1304f7b8d25811c66eb6163fba1f3fd1

**Comment by daftspunk** [comment]
Solution to fixing the interdependencies: 

Leverage the [TestMain function](https://golang.org/pkg/testing/#hdr-Main) to perform set up operations; create a base environment for the tests to work upon. This means creating the necessary common objects required to function, as opposed to relying on other tests to do it and relying on a specific execution order of each test. Each test should rely on this base state, provide modifications to it as part of its own testing and then clean up after itself (idempotent).

**Comment by KarlTheProgrammer** [comment]
I forgot to add the issue id in the commits, so here they are.

[Update tests.](https://github.com/tokenized/smart-contract/commit/49535b90750a8780dd2e3b4ae0ddc838fe3dc14a)
[Fix existing tests.](https://github.com/tokenized/smart-contract/commit/217942e538a781795e10b77f6d201d34d9c0a189)

**Comment by daftspunk** [comment]
Thanks!
