### ISSUE TITLE
Add contract id and tx id to logging prefix for traceability.

### ISSUE THREAD

**Issue by KarlTheProgrammer** [tokenized/smart-contract#9]
Rationale: This enables better tracing of transactions through the system and which contract (in a multi-contract system) is acting on them. It also makes the log entries more consistent with less code.

**Comment by KarlTheProgrammer** [comment]
I am open to suggestions.

The delimiter characters which are currently <>. I just want them to be different from any others used in the log entries. Right now the only others are the [] round the system name.

The location in the log entry. Right now it is after the log level so it is immediately before the free-form part of the log entry, but I could see it being before the level  or even file name.

The trace for smart contract is the first 5 bytes of the contract pkh and tx id in hex. I figure that is enough to be unique without cluttering up the entries too much. It can be different things for different applications.

**Comment by scottjbarr** [comment]
If you're still using a similar Context/logger (zap) setup, you should be
able to add these items as "fields" to the logger that is associated with
the context. Zap, apex (etc) do a great job of structured logging, and work
well when you need to add request id's and other data to the logger.

**Comment by KarlTheProgrammer** [comment]
We changed from zap to a custom logger. It is still context based, but allows for subsystem logging configuration. So that subsystems can log when we want them to.

**Comment by KarlTheProgrammer** [comment]
I moved the logger package usage inside the node package, changed the trace id, and added a trace data log entry like we talked about.

**Comment by daftspunk** [comment]
Very nice. Thanks!
